### ISSUE TITLE
test for webgl support

### ISSUE THREAD

**Issue by gitdemont** [daattali/shinybrowser#1]
Hi,

I just discovered your shinybrowser project.
It looks super cool !

I recently came into troubles using the amazing rgl R package into a shiny app I am currently developing.
This had nothing to do with rgl package itself but rather with webgl that was not supported by my browser.

I guess retrieving if webgl is available or not may be the kind of thing that could fall under the focus of your shinybrowser project

Actually, to test it*, I am using your fantastic shinyjs R package:
runjs(code = var canvas=document.createElement('canvas');var gl=canvas.getContext('webgl')||canvas.getContext('experimental-webgl');Shiny.setInputValue('webgl_available',!!(false | (gl && gl instanceof WebGLRenderingContext)));delete canvas; delete gl;")

*adapted from: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example/Detect_WebGL

I am doing it in a pretty ugly way creating global var and deleting it.
It will be better inside your shinybrowser function shinybrowser/inst/assets/srcjs/shinybrowser.js

to have something like:
var avlWebGL = function() {
  var canvas=document.createElement('canvas');
  var gl=canvas.getContext('webgl')||canvas.getContext('experimental-webgl');
  return !!(false | (gl && gl instanceof WebGLRenderingContext));
  };

Best,

**Comment by daattali** [comment]
Thanks for the suggestion, but I would not want to include webgl support as something shinybrowser looks for. There are dozens (hundreds?) of potential web features to look for, and it would get out of hand if I tried supporting that. Instead, shinybrowser is only meant to tell you what browser and environment the user is on.
