### ISSUE TITLE
Cannot figure out what versions of R this is compatable with.

### ISSUE THREAD

**Issue by MattWittbrodt** [daattali/shinybrowser#3]
4.0.2 and 4.1.0 do not appear to work. Cannot find documentation about compatibility.

**Comment by daattali** [comment]
I don't have R 4 installed on my machine. Does this package not work with R 4?

**Comment by MattWittbrodt** [comment]
Apologies - the remotes:: option works. Using install.packages() gives and error that shinybrowser does not work with 4.x.x. I tested with the same error also on 3.6. It could be my setup, though. Since the remotes:: option works, I closed the issue.

**Comment by daattali** [comment]
The package is not on CRAN yet, so install.packages won't work for anybody.
